### ISSUE TITLE
Gets a trouble loading from katana json file

### ISSUE THREAD

**Issue by hashem-mo** [3nock/SpiderSuite#3]
I go to Application/Import From/katana/json 
and when i load the json file it pops up says Importing from "D:/path/file.json" Complete

but i get nothing and it does not import it

**Comment by hashem-mo** [comment]
I also get this error at the logger view

[٠٢:٢٢:١٥] WARNING: QSslSocket::connectToHostEncrypted: TLS initialization failed
[٠٢:٢٢:١٥] WARNING: UPDATE CHECK: Network Error...

**Comment by 3nock** [comment]
For the SSL error, it is common to some windows machine which are missing some openssl library dll. Go to the installation folder of SpiderSuite and install openSSL using the openSSL installer which comes with SpiderSuite (**SpiderSuite/Win64OpenSSL_Light-1_1_1n.msi**)

For the loading issue, can I ask how large is the Json file?

One more question. Which version of SpiderSuite are you using?

**Comment by 3nock** [comment]
I think the error is related to the file size. The JSON parser I used in v1.0.0 and v1.0.1 had a limitation of only being able to parse files less than 125mb, but the current parser that I'm using has no such limitation. So for the coming versions you'll be able to load a file of any size.

Try loading a katana json file of less than 125mb to confirm this.

**Comment by hashem-mo** [comment]
Hi, You said that importing from other tools are fixed in 1.0.2V but unfortunately i still can not import Katana's json files, Although the file is not big at all Only 3.3MB

**Comment by 3nock** [comment]
Sorry for the late reply. I think the issue lies with the katana json file format, if possible can you upload a sample file.

**Comment by hashem-mo** [comment]
Yes sure, 
Github does not support json files so i could not upload it here but i uploaded it on drive and here is the link [https://drive.google.com/file/d/1vhNayOw_Hvv6831lCOxM4hEkG2uoEZJy/view?usp=sharing](url)

**Note**: i tried several times on other files and didn't work though

**Comment by 3nock** [comment]
Now I see where the problem was. 
SpiderSuite could only import katana json output files containing the requests & responses. So only katana crawls which were run with the `-sr, -store-response` flag.

Thank you for the feedback, it was very helpful. I'll add the capability of importing all types of katana crawl results in the comming version of SpiderSuite.

**Comment by hashem-mo** [comment]
Oh yes it worked very well.
Thanks for your efforts, the tool is great
